crumb-app/config/routes.rb
Rails.application.routes.draw do
  resources :crumbs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "crumbs#index"
end

crumb-app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

crumb-app/app/models/crumb.rb
class Crumb < ApplicationRecord
end

crumb-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

crumb-app/app/controllers/crumbs_controller.rb
class CrumbsController < ApplicationController
  before_action :set_crumb, only: [:show, :edit, :update, :destroy]

  # GET /crumbs
  # GET /crumbs.json
  def index
    @crumbs = Crumb.all
  end

  # GET /crumbs/1
  # GET /crumbs/1.json
  def show
  end

  # GET /crumbs/new
  def new
    @crumb = Crumb.new
  end

  # GET /crumbs/1/edit
  def edit
  end

  # POST /crumbs
  # POST /crumbs.json
  def create
    @crumb = Crumb.new(crumb_params)

    respond_to do |format|
      if @crumb.save
        format.html { redirect_to @crumb, notice: 'Crumb was successfully created.' }
        format.json { render :show, status: :created, location: @crumb }
      else
        format.html { render :new }
        format.json { render json: @crumb.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crumbs/1
  # PATCH/PUT /crumbs/1.json
  def update
    respond_to do |format|
      if @crumb.update(crumb_params)
        format.html { redirect_to @crumb, notice: 'Crumb was successfully updated.' }
        format.json { render :show, status: :ok, location: @crumb }
      else
        format.html { render :edit }
        format.json { render json: @crumb.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crumbs/1
  # DELETE /crumbs/1.json
  def destroy
    @crumb.destroy
    respond_to do |format|
      format.html { redirect_to crumbs_url, notice: 'Crumb was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crumb
      @crumb = Crumb.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crumb_params
      params.require(:crumb).permit(:crumb)
    end
end

crumb-app/app/helpers/application_helper.rb
module ApplicationHelper
end

crumb-app/app/helpers/crumbs_helper.rb
module CrumbsHelper
end

crumb-app/app/views/crumbs/_form.html.erb
<%= form_with(model: crumb, local: true) do |form| %>
  <% if crumb.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(crumb.errors.count, "error") %> prohibited this crumb from being saved:</h2>

      <ul>
      <% crumb.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :crumb %>
    <%= form.text_area :crumb %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

crumb-app/app/views/crumbs/edit.html.erb
<h1>Editing Crumb</h1>

<%= render 'form', crumb: @crumb %>

<%= link_to 'Show', @crumb %> |
<%= link_to 'Back', crumbs_path %>

crumb-app/app/views/crumbs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Crumbs</h1>

<table>
  <thead>
    <tr>
      <th>Crumb</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @crumbs.each do |crumb| %>
      <tr>
        <td><%= crumb.crumb %></td>
        <td><%= link_to 'Show', crumb %></td>
        <td><%= link_to 'Edit', edit_crumb_path(crumb) %></td>
        <td><%= link_to 'Destroy', crumb, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Crumb', new_crumb_path %>

crumb-app/app/views/crumbs/new.html.erb
<h1>New Crumb</h1>

<%= render 'form', crumb: @crumb %>

<%= link_to 'Back', crumbs_path %>

crumb-app/app/views/crumbs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Crumb:</strong>
  <%= @crumb.crumb %>
</p>

<%= link_to 'Edit', edit_crumb_path(@crumb) %> |
<%= link_to 'Back', crumbs_path %>

crumb-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrumbApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
    <div class="notification is-primary global-notification">
        <p class="notice"><%= notice %></p>
      </div>

    <% end %>
    <% if flash[:alert] %>
    <div class="notification is-danger global-notification">
      <p class="alert"><%= alert %></p>
    </div>
    <% end %>
    <%= yield %>
  </body>
</html>